fix qemu-system-x86-xen-hwe install
 qemu-system-x86-xen-hwe : Depends: qemu-system-xen-hwe (>= 1:7.0+dfsg-7ubuntu1) but it is not going to be installed
Error: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. qemu-system-xen-hwe:amd64=1:10.2.1+ds-1ubuntu1 is not selected for install because:
      1. qemu-system-x86-xen-hwe:amd64=1:10.2.1+ds-1ubuntu1 is selected for install
      2. qemu-system-x86-xen-hwe:amd64 Conflicts qemu-system-x86-xen
         [selected qemu-system-x86-xen-hwe:amd64]
   2. qemu-system-xen-hwe:amd64=1:10.2.1+ds-1ubuntu1 is selected for install because:
      1. qemu-system-x86-xen-hwe:amd64=1:10.2.1+ds-1ubuntu1 is selected for install as above
      2. qemu-system-x86-xen-hwe:amd64 Depends qemu-system-xen-hwe (>= 1:7.0+dfsg-7ubuntu1)
      3. qemu-system-xen-hwe:amd64 is available in version 1:10.2.1+ds-1ubuntu1